num_workers: 16
use_amp: true
sharded_ddp: false
num_att_plot: 0

lm: transformer_opt
lm_conf:
    opt_name: facebook/opt-350m
    local_files_only: false
    
model: lm_multitask
model_conf:
    lsm_weight: 0.01
    length_normalized_loss: true
    sos_syms:   # multiple sos symbols are used
    - "<generatetext>"
    - "<generatespeech>"
    eos_sym: "<sos/eos>"

# optimization related
grad_clip: 1.0
batch_type: length
batch_bins: 10000
accum_grad: 40
num_iters_per_epoch: 12500
max_epoch: 70

optim: adam
optim_conf:
   lr: 0.0003
   weight_decay: 1.0e-06
scheduler: warmuplr
scheduler_conf:
   warmup_steps: 2500

best_model_criterion:
-   - valid
    - acc
    - max
keep_nbest_models: 10
