num_workers: 16
use_amp: true
sharded_ddp: false
num_att_plot: 0

lm: transformer_opt
lm_conf:
    opt_name: /projects/p32222/ylu125/model_weight/softmax1_opt
    local_files_only: true
    

model: lm_multitask
model_conf:
    lsm_weight: 0.1
    length_normalized_loss: true
    sos_syms:   # multiple sos symbols are used
    - "<generatetext>"
    - "<generatespeech>"
    eos_sym: "<sos/eos>"

# optimization related
grad_clip: 1.0
batch_type: length
batch_bins: 25000
accum_grad: 8
num_iters_per_epoch: 5000
max_epoch: 67


optim: adam
optim_conf:
   lr: 0.0003
   weight_decay: 1.0e-06
scheduler: warmuplr
scheduler_conf:
   warmup_steps: 2500

best_model_criterion:
-   - valid
    - acc
    - max
keep_nbest_models: 10
